openapi: 3.0.0
info:
  description: This is the merged OpenAPI specification.
  version: "4.0"
  title: XCom.API
  contact:
    email: phil.hotchkiss@veteransunited.com
tags:
  - name: mail
  - name: connect
  - name: template-sets
paths:
  /template-sets:
    post:
      tags:
        - template-sets
      summary: Create a template set
      operationId: createTemplateSet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TemplateSet'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemplateSetCreateSuccessResponse'
    get:
      tags:
        - template-sets
      summary: Get template sets by query parameters
      operationId: queryTemplateSets
      parameters:
        - in: query
          name: sendGridTemplateId
          required: false
          schema:
            type: string
        - in: query
          name: templateSetName
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryTemplateSetSuccessResponse'
  /template-sets/{id}:
    get:
      tags:
        - template-sets
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: guid
      summary: Get a template set
      operationId: getTemplateSet
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTemplateSetSuccessResponse'
    patch:
      tags:
        - template-sets
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: guid
      summary: Update a template set
      operationId: updateTemplateSet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TemplateSet'
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    TemplateSet:
      type: object
      properties:
        templateSetName:
          type: string
        categories:
          type: array
          items:
            type: string
    TemplateSetCreateSuccessResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/SuccessResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/TemplateSetCreateSuccessResponseData'
    SuccessResponse:
      type: object
      properties:
        apiVersion:
          type: string
        id:
          type: string
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
