:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\XCom
dotnet build src\XCom
echo Now, run the following to start the project: dotnet run -p src\XCom\XCom.csproj --launch-profile web.
echo.
