/*
 * XCom.API
 *
 * This API is responsible for enabling communication with SendGrid. It implements additional features such as data retention and A/B Testing for specific templates
 *
 * The version of the OpenAPI document: 4.0
 * Contact: phil.hotchkiss@veteransunited.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using XCom.Converters;

namespace XCom.Models
{ 
        /// <summary>
        /// Gets or Sets WebhookEvent
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<WebhookEvent>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum WebhookEvent
        {
            
            /// <summary>
            /// Enum ProcessedEnum for Processed
            /// </summary>
            [EnumMember(Value = "Processed")]
            ProcessedEnum = 1,
            
            /// <summary>
            /// Enum DroppedEnum for Dropped
            /// </summary>
            [EnumMember(Value = "Dropped")]
            DroppedEnum = 2,
            
            /// <summary>
            /// Enum DeliveredEnum for Delivered
            /// </summary>
            [EnumMember(Value = "Delivered")]
            DeliveredEnum = 3,
            
            /// <summary>
            /// Enum DeferredEnum for Deferred
            /// </summary>
            [EnumMember(Value = "Deferred")]
            DeferredEnum = 4,
            
            /// <summary>
            /// Enum BounceEnum for Bounce
            /// </summary>
            [EnumMember(Value = "Bounce")]
            BounceEnum = 5,
            
            /// <summary>
            /// Enum OpenEnum for Open
            /// </summary>
            [EnumMember(Value = "Open")]
            OpenEnum = 6,
            
            /// <summary>
            /// Enum ClickEnum for Click
            /// </summary>
            [EnumMember(Value = "Click")]
            ClickEnum = 7,
            
            /// <summary>
            /// Enum SpamReportEnum for SpamReport
            /// </summary>
            [EnumMember(Value = "SpamReport")]
            SpamReportEnum = 8,
            
            /// <summary>
            /// Enum UnsubscribeEnum for Unsubscribe
            /// </summary>
            [EnumMember(Value = "Unsubscribe")]
            UnsubscribeEnum = 9,
            
            /// <summary>
            /// Enum GroupUnsubscribeEnum for Group_Unsubscribe
            /// </summary>
            [EnumMember(Value = "Group_Unsubscribe")]
            GroupUnsubscribeEnum = 10,
            
            /// <summary>
            /// Enum GroupResubscribeEnum for Group_Resubscribe
            /// </summary>
            [EnumMember(Value = "Group_Resubscribe")]
            GroupResubscribeEnum = 11
        }
}
